# Generated by Django 6.0.1 on 2026-01-28 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_service', '0001_initial'),
        ('pharmacies', '0002_alter_pharmacy_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='nearest_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_hits', to='pharmacies.pharmacy'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL),
        ),
    ]
