# Generated by Django 6.0.1 on 2026-01-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pharmacies', '0002_alter_pharmacy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacies.pharmacy'),
        ),
    ]
